export interface QuestDef {
  key: string
  title: string
  description: string
  reward: number
  type: "daily" | "weekly" | "progression"
  total_free: number
  total_premium: number
  icon: string
  is_premium: boolean // true = premium-only quest
}

export const QUEST_DEFINITIONS: QuestDef[] = [
  // ── Quotidiennes ─────────────────────────────────────────────
  {
    key: "daily_login",
    title: "Connexion du jour",
    description: "Connecte-toi aujourd'hui",
    reward: 1,
    type: "daily",
    total_free: 1,
    total_premium: 1,
    icon: "ti-calendar",
    is_premium: false,
  },
  {
    key: "daily_bets",
    title: "Parieur actif",
    description: "Pose des paris aujourd'hui",
    reward: 3,
    type: "daily",
    total_free: 5,
    total_premium: 2,
    icon: "ti-bolt",
    is_premium: false,
  },
  {
    key: "daily_live",
    title: "Pari live",
    description: "Pose des paris en direct",
    reward: 5,
    type: "daily",
    total_free: 3,
    total_premium: 1,
    icon: "ti-live-photo",
    is_premium: true,
  },
  {
    key: "daily_combi",
    title: "Combiné du jour",
    description: "Réalise un combiné de matchs",
    reward: 4,
    type: "daily",
    total_free: 4,
    total_premium: 2,
    icon: "ti-layout-grid",
    is_premium: false,
  },
  {
    key: "daily_win",
    title: "Paris gagnant",
    description: "Gagne des paris aujourd'hui",
    reward: 5,
    type: "daily",
    total_free: 3,
    total_premium: 1,
    icon: "ti-trophy",
    is_premium: false,
  },

  // ── Hebdomadaires ─────────────────────────────────────────────
  {
    key: "weekly_streak",
    title: "Régularité",
    description: "Parie plusieurs jours d'affilée",
    reward: 20,
    type: "weekly",
    total_free: 7,
    total_premium: 4,
    icon: "ti-flame",
    is_premium: false,
  },
  {
    key: "weekly_combi",
    title: "Combineur",
    description: "Réalise des combinés cette semaine",
    reward: 15,
    type: "weekly",
    total_free: 5,
    total_premium: 2,
    icon: "ti-layout-columns",
    is_premium: false,
  },
  {
    key: "weekly_wins",
    title: "Série gagnante",
    description: "Gagne des paris cette semaine",
    reward: 20,
    type: "weekly",
    total_free: 5,
    total_premium: 2,
    icon: "ti-star",
    is_premium: false,
  },
  {
    key: "weekly_social",
    title: "Social",
    description: "Invite un ami dans une ligue",
    reward: 10,
    type: "weekly",
    total_free: 0, // unavailable free
    total_premium: 1,
    icon: "ti-users",
    is_premium: true,
  },
  {
    key: "weekly_explorer",
    title: "Explorateur",
    description: "Parie sur plusieurs compétitions",
    reward: 15,
    type: "weekly",
    total_free: 5,
    total_premium: 3,
    icon: "ti-world",
    is_premium: false,
  },

  // ── Progression ───────────────────────────────────────────────
  {
    key: "profile_complete",
    title: "Profil complet",
    description: "Complète ton profil (pseudo + avatar)",
    reward: 5,
    type: "progression",
    total_free: 1,
    total_premium: 1,
    icon: "ti-user-check",
    is_premium: false,
  },
  {
    key: "first_combi",
    title: "Premier combiné",
    description: "Pose ton premier combiné",
    reward: 5,
    type: "progression",
    total_free: 1,
    total_premium: 1,
    icon: "ti-layout-grid",
    is_premium: false,
  },
  {
    key: "first_win",
    title: "Premier gain",
    description: "Gagne ton premier pari",
    reward: 5,
    type: "progression",
    total_free: 1,
    total_premium: 1,
    icon: "ti-trophy",
    is_premium: false,
  },
  {
    key: "balance_x2",
    title: "Solde x2",
    description: "Atteins 100 Bluffs",
    reward: 20,
    type: "progression",
    total_free: 100,
    total_premium: 100,
    icon: "ti-coins",
    is_premium: false,
  },
  {
    key: "balance_x5",
    title: "Solde x5",
    description: "Atteins 250 Bluffs",
    reward: 50,
    type: "progression",
    total_free: 250,
    total_premium: 250,
    icon: "ti-diamond",
    is_premium: false,
  },
  {
    key: "grand_parieur",
    title: "Grand parieur",
    description: "Pose de nombreux paris",
    reward: 30,
    type: "progression",
    total_free: 100,
    total_premium: 50,
    icon: "ti-ticket",
    is_premium: false,
  },
  {
    key: "fidele",
    title: "Fidèle",
    description: "Connecte-toi régulièrement",
    reward: 25,
    type: "progression",
    total_free: 30,
    total_premium: 15,
    icon: "ti-heart",
    is_premium: false,
  },
  {
    key: "all_in",
    title: "All-in",
    description: "Mise 20B sur un seul pari",
    reward: 10,
    type: "progression",
    total_free: 1,
    total_premium: 1,
    icon: "ti-poker-chip",
    is_premium: false,
  },
]
