/**
 * Mapping des équipes de football (clubs et nations) vers codes pays ISO 2
 * Utilisé pour afficher les drapeaux appropriés
 */

// Nations - Coupe du Monde, Euro, Copa America, etc.
export const NATIONAL_TEAMS: Record<string, string> = {
  // Europe
  "France": "FR",
  "Germany": "DE",
  "Allemagne": "DE",
  "Spain": "ES",
  "Espagne": "ES",
  "Italy": "IT",
  "Italie": "IT",
  "England": "GB",
  "Angleterre": "GB",
  "Portugal": "PT",
  "Netherlands": "NL",
  "Pays-Bas": "NL",
  "Belgium": "BE",
  "Belgique": "BE",
  "Switzerland": "CH",
  "Suisse": "CH",
  "Austria": "AT",
  "Autriche": "AT",
  "Sweden": "SE",
  "Suède": "SE",
  "Norway": "NO",
  "Norvège": "NO",
  "Denmark": "DK",
  "Danemark": "DK",
  "Finland": "FI",
  "Finlande": "FI",
  "Poland": "PL",
  "Pologne": "PL",
  "Czech Republic": "CZ",
  "République Tchèque": "CZ",
  "Tchéquie": "CZ",
  "Slovakia": "SK",
  "Slovaquie": "SK",
  "Hungary": "HU",
  "Hongrie": "HU",
  "Romania": "RO",
  "Roumanie": "RO",
  "Croatia": "HR",
  "Croatie": "HR",
  "Slovenia": "SI",
  "Slovénie": "SI",
  "Greece": "GR",
  "Grèce": "GR",
  "Ukraine": "UA",
  "Russia": "RU",
  "Russie": "RU",
  "Turkey": "TR",
  "Turquie": "TR",
  "Ireland": "IE",
  "Irlande": "IE",
  "Iceland": "IS",
  "Islande": "IS",
  "Serbia": "RS",
  "Serbie": "RS",
  "Bosnia": "BA",
  "Bosnie": "BA",
  "Montenegro": "ME",
  "Monténégro": "ME",
  "Albania": "AL",
  "Albanie": "AL",
  "North Macedonia": "MK",
  "Macédoine du Nord": "MK",
  "Bulgaria": "BG",
  "Bulgarie": "BG",
  "Moldova": "MD",
  "Moldavie": "MD",
  "Georgia": "GE",
  "Géorgie": "GE",
  "Armenia": "AM",
  "Arménie": "AM",
  "Azerbaijan": "AZ",
  "Azerbaïdjan": "AZ",
  "Belarus": "BY",
  "Biélorussie": "BY",
  "Lithuania": "LT",
  "Lituanie": "LT",
  "Latvia": "LV",
  "Lettonie": "LV",
  "Estonia": "EE",
  "Estonie": "EE",
  "Luxembourg": "LU",
  "Malta": "MT",
  "Malte": "MT",
  "Cyprus": "CY",
  "Chypre": "CY",
  "Kosovo": "XK",
  "Wales": "GB",
  "Pays de Galles": "GB",
  "Scotland": "GB",
  "Écosse": "GB",
  "Northern Ireland": "GB",
  "Irlande du Nord": "GB",

  // Americas
  "United States": "US",
  "USA": "US",
  "États-Unis": "US",
  "United States of America": "US",
  "America": "US",
  "Canada": "CA",
  "Mexico": "MX",
  "Mexique": "MX",
  "Brazil": "BR",
  "Brésil": "BR",
  "Argentina": "AR",
  "Argentine": "AR",
  "Chile": "CL",
  "Chili": "CL",
  "Colombia": "CO",
  "Colombie": "CO",
  "Peru": "PE",
  "Pérou": "PE",
  "Uruguay": "UY",
  "Paraguay": "PY",
  "Paraguai": "PY",
  "Venezuela": "VE",
  "Ecuador": "EC",
  "Équateur": "EC",
  "Bolivia": "BO",
  "Bolivie": "BO",
  "Costa Rica": "CR",
  "Honduras": "HN",
  "El Salvador": "SV",
  "Salvador": "SV",
  "Guatemala": "GT",
  "Panama": "PA",
  "Jamaica": "JM",
  "Jamaïque": "JM",
  "Trinidad and Tobago": "TT",
  "Trinité-et-Tobago": "TT",
  "Haiti": "HT",
  "Haïti": "HT",
  "Dominican Republic": "DO",
  "République Dominicaine": "DO",
  "Belize": "BZ",
  "Suriname": "SR",
  "Guyana": "GY",
  "Guyane": "GY",
  "Nicaragua": "NI",
  "Curacao": "CW",
  "Curaçao": "CW",
  "Curaçao": "CW",

  // Asia
  "China": "CN",
  "Chine": "CN",
  "Japan": "JP",
  "Japon": "JP",
  "South Korea": "KR",
  "Corée du Sud": "KR",
  "North Korea": "KP",
  "Corée du Nord": "KP",
  "India": "IN",
  "Inde": "IN",
  "Thailand": "TH",
  "Thaïlande": "TH",
  "Malaysia": "MY",
  "Malaisie": "MY",
  "Singapore": "SG",
  "Singapour": "SG",
  "Philippines": "PH",
  "Vietnam": "VN",
  "Viêtnam": "VN",
  "Indonesia": "ID",
  "Indonésie": "ID",
  "Taiwan": "TW",
  "Taïwan": "TW",
  "Hong Kong": "HK",
  "Bangladesh": "BD",
  "Pakistan": "PK",
  "Sri Lanka": "LK",
  "Iran": "IR",
  "Iraq": "IQ",
  "Saudi Arabia": "SA",
  "Arabie Saoudite": "SA",
  "United Arab Emirates": "AE",
  "Émirats Arabes Unis": "AE",
  "Qatar": "QA",
  "Kuwait": "KW",
  "Koweït": "KW",
  "Bahrain": "BH",
  "Bahreïn": "BH",
  "Oman": "OM",
  "Oman": "OM",
  "Jordan": "JO",
  "Jordanie": "JO",
  "Lebanon": "LB",
  "Liban": "LB",
  "Syria": "SY",
  "Syrie": "SY",
  "Palestine": "PS",
  "Israel": "IL",
  "Israël": "IL",
  "Afghanistan": "AF",
  "Afghanistan": "AF",

  // Africa
  "Egypt": "EG",
  "Égypte": "EG",
  "Morocco": "MA",
  "Maroc": "MA",
  "Tunisia": "TN",
  "Tunisie": "TN",
  "Algeria": "DZ",
  "Algérie": "DZ",
  "South Africa": "ZA",
  "Afrique du Sud": "ZA",
  "Nigeria": "NG",
  "Ghana": "GH",
  "Kenya": "KE",
  "Cameroon": "CM",
  "Cameroun": "CM",
  "Ivory Coast": "CI",
  "Côte d'Ivoire": "CI",
  "Cote d'Ivoire": "CI",
  "Senegal": "SN",
  "Sénégal": "SN",
  "Mali": "ML",
  "Burkina Faso": "BF",
  "Burkina": "BF",
  "Guinea": "GN",
  "Guinée": "GN",
  "Sierra Leone": "SL",
  "Liberia": "LR",
  "Benin": "BJ",
  "Bénin": "BJ",
  "Togo": "TG",
  "Ethiopia": "ET",
  "Éthiopie": "ET",
  "Uganda": "UG",
  "Ouganda": "UG",
  "Rwanda": "RW",
  "Tanzania": "TZ",
  "Tanzanie": "TZ",
  "Zimbabwe": "ZW",
  "Zambia": "ZM",
  "Zambie": "ZM",
  "Botswana": "BW",
  "Lesotho": "LS",
  "Namibia": "NA",
  "Namibie": "NA",
  "Angola": "AO",
  "Mozambique": "MZ",
  "Malawi": "MW",

  // Oceania
  "Australia": "AU",
  "Australie": "AU",
  "New Zealand": "NZ",
  "Nouvelle-Zélande": "NZ",

  // Clubs de football - utiliser le pays de la ligue ou du siège
  "PSG": "FR",
  "Paris": "FR",
  "Lille": "FR",
  "Marseille": "FR",
  "Lyon": "FR",
  "Lens": "FR",
  "Nice": "FR",
  "Monaco": "FR",
  "Rennes": "FR",
  "Bordeaux": "FR",

  "Manchester United": "GB",
  "Manchester City": "GB",
  "Liverpool": "GB",
  "Arsenal": "GB",
  "Chelsea": "GB",
  "Tottenham": "GB",
  "Newcastle": "GB",
  "Brighton": "GB",

  "Real Madrid": "ES",
  "Barcelona": "ES",
  "Atletico Madrid": "ES",
  "Sevilla": "ES",
  "Valencia": "ES",
  "Villarreal": "ES",

  "Bayern Munich": "DE",
  "Borussia Dortmund": "DE",
  "Bayer Leverkusen": "DE",
  "RB Leipzig": "DE",
  "Schalke": "DE",
  "Union Berlin": "DE",

  "Juventus": "IT",
  "AC Milan": "IT",
  "Inter Milan": "IT",
  "Roma": "IT",
  "Napoli": "IT",
  "Lazio": "IT",
  "Fiorentina": "IT",
  "Atalanta": "IT",

  "Benfica": "PT",
  "Porto": "PT",
  "Sporting CP": "PT",

  "Ajax": "NL",
  "PSV": "NL",
  "Feyenoord": "NL",

  "Anderlecht": "BE",
  "Club Brugge": "BE",

  "Zurich": "CH",
  "Basel": "CH",
  "Young Boys": "CH",

  "Celtic": "GB",
  "Rangers": "GB",

  "Olympiacos": "GR",
  "AEK Athens": "GR",

  "Shakhtar Donetsk": "UA",
  "Dynamo Kyiv": "UA",

  "CSKA Moscow": "RU",
  "Spartak Moscow": "RU",

  "Galatasaray": "TR",
  "Fenerbahce": "TR",
  "Besiktas": "TR",
}

/**
 * Normalize team name for matching (remove accents, lowercase, trim)
 */
function normalizeTeamName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // Remove accents
    .trim()
}

/**
 * Obtient le code pays pour une équipe
 */
export function getCountryCodeForTeam(teamName?: string): string | null {
  if (!teamName) return null

  // Exact match first
  if (NATIONAL_TEAMS[teamName]) {
    return NATIONAL_TEAMS[teamName]
  }

  // Normalized match (ignore accents and case)
  const normalizedInput = normalizeTeamName(teamName)
  for (const [key, code] of Object.entries(NATIONAL_TEAMS)) {
    if (normalizeTeamName(key) === normalizedInput) {
      return code
    }
  }

  return null
}

/**
 * Détecte si c'est un match international basé sur la compétition
 */
export function isInternationalCompetition(competition?: string): boolean {
  const internationalComps = ["CDM", "EUR", "COPA", "AFCON", "ACN", "GOLD", "CONMEBOL"]
  return competition ? internationalComps.some(c => competition.includes(c)) : false
}
