-- Create quest_progress table for tracking user progress on quests
CREATE TABLE IF NOT EXISTS quest_progress (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  quest_key TEXT NOT NULL,
  period_key TEXT NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  is_done BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (user_id, quest_key, period_key)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_quest_progress_user_id ON quest_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_quest_progress_user_quest_period ON quest_progress(user_id, quest_key, period_key);

-- Enable RLS
ALTER TABLE quest_progress ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS quest_progress_select_own ON quest_progress;
DROP POLICY IF EXISTS quest_progress_update_own ON quest_progress;
DROP POLICY IF EXISTS quest_progress_insert_own ON quest_progress;
DROP POLICY IF EXISTS quest_progress_service_role ON quest_progress;

-- RLS Policies
CREATE POLICY quest_progress_select_own ON quest_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY quest_progress_insert_own ON quest_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY quest_progress_update_own ON quest_progress FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY quest_progress_service_role ON quest_progress FOR ALL USING (auth.role() = 'service_role');
